server.port: 8081

spring.datasource.read:
  driver-class-name: org.sqlite.JDBC
  url: jdbc:sqlite:read.db
  username: root
  password: root

  initial-size: 2
  max-active: 10
  min-idle: 3
  max-idle: 6
  #查询超时（单位：秒）
  query-timeout: 5

  test-on-borrow: true
  test-while-idle: true
  validation-query: select 1
  #验证超时（单位：秒）
  validation-query-timeout: 1

#  remove-abandoned: true
#  log-abandoned: true
#  remove-abandoned-timeout: 600



spring.datasource.write:
  driver-class-name: org.sqlite.JDBC
  url: jdbc:sqlite:write.db
  username: root
  password: root

  filters: stat